### ISSUE TITLE
Using AstralHaze Crashes

### ISSUE THREAD

**Issue by daviscook477** [gskleres/FruityMod-StS#1]
Log:
```
Exception: java.lang.NullPointerException
01:07:22.118 [LWJGL Application] ERROR com.megacrit.cardcrawl.core.CardCrawlGame - Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.vfx.combat.FlashPowerEffect.<init>(FlashPowerEffect.java:29) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.powers.AbstractPower.flash(AbstractPower.java:371) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.actions.common.ApplyPowerAction.update(ApplyPowerAction.java:270) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:139) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:241) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2384) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:770) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:366) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Game closed.
```

**Comment by daviscook477** [comment]
I fixed this one
