### ISSUE TITLE
Game crashes on unlocks

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#114]
BUG: Game repeatedly crashes on beating a boss and unlocking new cards.

**Comment by daviscook477** [comment]
do we have an actual crash log for this anywhere?

**Comment by daviscook477** [comment]
Seems fixed in latest builds

**Comment by daviscook477** [comment]
```
Exception: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12:36:29.689 ERROR core.CardCrawlGame> Exception caught
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_162]
    at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_162]
    at com.megacrit.cardcrawl.gashapon.GashaUnlockScreen.open(GashaUnlockScreen.java:56) ~[desktop-1.0.jar:?]
    at com.megacrit.cardcrawl.screens.DeathScreen.update(DeathScreen.java:945) ~[?:?]
    at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2487) ~[?:?]
    at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:782) ~[?:?]
    at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:374) [?:?]
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
```

Crash report ^ courtesy of @fiiiiilth

**Comment by daviscook477** [comment]
Should actually be fixed with the newest changes to BaseMod.
