### ISSUE TITLE
Brainstorm causes Exception

### ISSUE THREAD

**Issue by Lunaraia** [gskleres/FruityMod-StS#118]
xception: java.lang.NullPointerException
13:33:02.936 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at java.io.StringReader.<init>(Unknown Source) ~[?:1.8.0_162]
	at java.util.Scanner.<init>(Unknown Source) ~[?:1.8.0_162]
	at com.megacrit.cardcrawl.cards.AbstractCard.initializeDescription(AbstractCard.java:387) ~[?:?]
	at fruitymod.cards.Brainstorm.upgrade(Brainstorm.java:56) ~[FruityMod.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.getRewardCards(AbstractDungeon.java:1854) ~[?:?]
	at com.megacrit.cardcrawl.rewards.RewardItem.<init>(RewardItem.java:128) ~[?:?]
	at com.megacrit.cardcrawl.screens.CombatRewardScreen.setupItemReward(CombatRewardScreen.java:75) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.screens.CombatRewardScreen.open(CombatRewardScreen.java:305) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:342) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2435) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:782) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:374) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Game closed.

from the looks of things the game crashes when trying to give Brainstorm/Brainstorm+ as a card reward.

**Comment by daviscook477** [comment]
I think I fixed this one

**Comment by Lunaraia** [comment]
I got it just before posting so if you did the fix has not been released yet

**Comment by daviscook477** [comment]
What build are you on?

**Comment by Lunaraia** [comment]
Mod The Spire 2.4.0
BaseMod 1.8.0
FruityMod 0.4.3
Colored Map 1.2.1
MoreRelics 1.2.0

Early Access Build (03-01-2018)

**Comment by daviscook477** [comment]
We've definitely had some additional releases to FruityMod since then. The latest build shouldn't crash. https://github.com/gskleres/FruityMod-StS/releases

**Comment by Lunaraia** [comment]
can't say if it's fixed or not since I didn't get a brainstorm in rewards, but it DID fix the double cards from Dead Branch, not sure what you did there but it worked wonders, will close this once I run into one and can confirm that it's fixed.

**Comment by daviscook477** [comment]
Great thanks!

**Comment by daviscook477** [comment]
I'm going to close this one as fixed since we haven't had any issue since.

**Comment by Lunaraia** [comment]
it's more the fact I haven't SEEN brainstorm since as in it's as if the card does not exist anymore
