### ISSUE TITLE
Not sure wether this is BaseMod or FruityMod so posting it at both

### ISSUE THREAD

**Issue by Lunaraia** [gskleres/FruityMod-StS#146]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.evacipated.cardcrawl.modthespire.Patcher.initializeMods(Patcher.java:32)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:154)
	at com.evacipated.cardcrawl.modthespire.ModSelectWindow.lambda$null$1(ModSelectWindow.java:71)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at basemod.BaseMod.subscribeToPostInitialize(BaseMod.java:2067)
	at fruitymod.FruityMod.<init>(FruityMod.java:354)
	at fruitymod.FruityMod.initialize(FruityMod.java:401)
	... 8 more

**Comment by gskleres** [comment]
@Lunaraia can you explain when this happened? any circumstances or such?

**Comment by Lunaraia** [comment]
it happened on startup before the game even began, only thing I did was getting the newest version of fruityMod and BaseMod and that happened

**Comment by Lunaraia** [comment]
Found the issue, when I updated my mods last time the load order got messed up and it made the Mods freak out causing the crash, found that out after I changed the load order of the mods out of idle curiosity
