### ISSUE TITLE
A list of issues from yesterday Seeker marathon

### ISSUE THREAD

**Issue by SirHaesslich** [gskleres/FruityMod-StS#189]
1) Doubt(and probably other curses too, did not have the chance to test) is bugged: it does not work. Maybe it has something to do with his starting relic, but never once did it give me Weakness after ending up in my hand after the turn. If the bug will fail to reproduce, try to put it in-and-out of the Top-Cycle option when offered by the Arcanosphere and THEN end the turn with the curse still unrecycled.

2) Umbra is a skill that can deal damage if the hero is weakened...but Weakness affects only attack damage yet it did reduce the damage of Umbra. It also dealt more damage when the target was vulnerable, but on top of that it still did not proc Guardian's thorn effect despite behaving like an attack in any other regard. Not that it works terribly counter-intuitively, but maybe changing it to Attack would solve its effect's conflict with the game rules, since block provided by attacks is still affected by Frail; it won't even change the card's effect apart from making it Spike-able/Thorn-able

3) Blueberries seems weird. That is not much of an issue, it just burned my butt to get exactly 1 maxHP off of it, so I naturally thought it will give me more if I put ethereal cards in the deck(not the Dazes middle-match, of course, but the reward cards to add to the actual deck). But it did not, which makes it not only very inconsistent with its benefit for a player, but also a very weak relic - decks are rarely fatter than 30 cards, and hardly more than 20 of them will be Ethereal even with this class, so the average buff is very small especially if you take into account the chance to get Blueberries early, when you physically cannot have more that 3-5 Ethereals, which will in turn deny you the possibility to pick them up later to maybe receive an at least somewhat substantial upgrade. I do not even think that giving 1 maxHP for every Ethereal pickup is OP, after all, look at Singing Bowl....

4) The game crashed. It happened on the City fight with either Chosen+Byrd or Chosen+Cultist. When I restarted the mod it offered an option to continue the run, but it crashed again as soon as the image of the hero and the enemies loaded. Among suggestions why it could happen - try Toolbox, it killed many mods other than this, although it was functioning well until this fight(maybe a particular card from it is the reason?). Sadly, I cannot remember it with more details, but I could look for it in the history if you will request more information.

**Comment by fiiiiilth** [comment]
@SirHaesslich Thanks for letting me know about these issues, I'll look into them soon.

Blueberries, I believe the intention was indeed to have it continue to give you hp on picking up new Ethereal cards, I'll have to check the design docs again. I believe at the time there was some technical issues there or something.

As for the game crash, if you could do me a huge favor and enable the "debug" option in ModTheSpire, and try to recreate that crash and copy the exception at the end, or look through the "sendToDevs" folder in your StS directory and try to find the logs with the exceptions. That should tell me more or less exactly what was causing it.

**Comment by fiiiiilth** [comment]
@SirHaesslich Ah, according to [this issue](https://github.com/gskleres/FruityMod-StS/issues/137) it appears Fruitstrike thinks Blueberries is fine as is. 

I disagree, picking up this relic with, for example, your starting deck and only ever getting 1 max hp makes it almost certainly the worst relic in the game. 

At the very least, the current text is indeed misleading.

**Comment by SirHaesslich** [comment]
17:42:53.208 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at fruitymod.cards.Dazed_P.updateEnigmaValue(Dazed_P.java:52)
~[FruityMod.jar:?]
	at fruitymod.cards.Dazed_P.applyPowers(Dazed_P.java:43) ~[FruityMod.jar:?]
	at com.megacrit.cardcrawl.cards.CardGroup.applyPowers(CardGroup.java:182)
~[?:?]
	at com.megacrit.cardcrawl.vfx.cardManip.ShowCardAndAddToHandEffect.<init>(ShowCardAndAddToHandEffect.java:58)
~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.actions.common.MakeTempCardInHandAction.addToHand(MakeTempCardInHandAction.java:85)
~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.actions.common.MakeTempCardInHandAction.update(MakeTempCardInHandAction.java:62)
~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:149)
~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:250)
~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2569)
~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:778)
~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:371)
[?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
[?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
[desktop-1.0.jar:?]
17:42:53.982 INFO helpers.FileSaver> Save thread interrupted!


17:40:49.446 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at fruitymod.cards.Dazed_P.updateEnigmaValue(Dazed_P.java:52)
~[FruityMod.jar:?]
	at fruitymod.cards.Dazed_P.applyPowers(Dazed_P.java:43) ~[FruityMod.jar:?]
	at com.megacrit.cardcrawl.cards.CardGroup.applyPowers(CardGroup.java:182)
~[?:?]
	at com.megacrit.cardcrawl.vfx.cardManip.ShowCardAndAddToHandEffect.<init>(ShowCardAndAddToHandEffect.java:58)
~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.actions.common.MakeTempCardInHandAction.addToHand(MakeTempCardInHandAction.java:85)
~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.actions.common.MakeTempCardInHandAction.update(MakeTempCardInHandAction.java:62)
~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:149)
~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:250)
~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2569)
~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:778)
~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:371)
[?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
[?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
[desktop-1.0.jar:?]
17:40:49.960 INFO helpers.FileSaver> Save thread interrupted!


Those seem to be those two attempts to fight. There were also lots of
ConnectTimeOut exceptions, but I figure that is just failed attempts
to connect to Steam

2018-05-17 19:29 GMT+03:00, fiiiiilth <notifications@github.com>:

**Comment by fiiiiilth** [comment]
@SirHaesslich Thanks, that helps immensely.

The issue is Toolbox is trying to give you "Dazed_P" (since it is technically a colorless card) and the Dazed_P can't "updateEnigmaValue()" as you don't have EnigmaPower active. 

Someone should fix that. ;p

**Comment by fiiiiilth** [comment]
@SirHaesslich Alright, I published a [new release](https://github.com/gskleres/FruityMod-StS/releases/tag/v0.6.3b) .

And here's [a list of changes](https://github.com/gskleres/FruityMod-StS/compare/v0.6.2b...master) between the previous build and the new one.

**Comment by SirHaesslich** [comment]
Wow that is the fix agility that would make MegaCrit themselves proud! :)
You guys are awesome

2018-05-17 21:30 GMT+03:00, fiiiiilth <notifications@github.com>:

**Comment by SirHaesslich** [comment]
And now for the most enraging part of programming which is fixing the fixed.

02:37:55.679 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at fruitymod.cards.Dazed_P.updateEnigmaValue(Dazed_P.java:55)
~[FruityMod.jar:?]
	at fruitymod.cards.Dazed_P.update(Dazed_P.java:67) ~[FruityMod.jar:?]
	at com.megacrit.cardcrawl.screens.CardRewardScreen.cardSelectUpdate(CardRewardScreen.java:80)
~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.screens.CardRewardScreen.update(CardRewardScreen.java:74)
~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2601)
~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:777)
~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:370)
[?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
[?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
[desktop-1.0.jar:?]

I am afraid a new crash-inducing bug has spawned :(

2018-05-17 22:43 GMT+03:00, Sir Hasslich <3danonym@gmail.com>:

**Comment by fiiiiilth** [comment]
I'm an idiot. Of course it was going to be offered at card reward screens. I might have to just rewrite Dazed_P. Enigma is the bane of my existence. -.-

**Comment by fiiiiilth** [comment]
@SirHaesslich hotfix released, sorry for all the crashes!

https://github.com/gskleres/FruityMod-StS/releases/tag/v0.6.4b

**Comment by SirHaesslich** [comment]
It is all for the better rite? :D
Thanks again!

2018-05-18 4:07 GMT+03:00, fiiiiilth <notifications@github.com>:
