### ISSUE TITLE
Essence Dart + Unc Top crash?

### ISSUE THREAD

**Issue by SirHaesslich** [gskleres/FruityMod-StS#190]
I was fighting a big slime with unceasing top as a first relic(INCEPTION seed), and the fight crashed when I ended up topdecking Essence Dart into an empty hand(that, obviously, could not be played) and ending the turn. During that I was under the Retain Energy effect similar to Icecream, but given from potion from another mod. So yeah, that might be not your bug and if so, I am very sorry, but the crashlog mentioned your mod, so I decided to give it a try

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.actions.common.MakeTempCardInDrawPileAction.<init>(Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/cards/AbstractCard;IZZ)V
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.actions.common.MakeTempCardInDrawPileAction.<init>(Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/cards/AbstractCard;IZZ)V
	at fruitymod.powers.RetrogradePower.atEndOfTurn(RetrogradePower.java:39)
	at fruitymod.characters.TheSeeker.applyEndOfTurnTriggers(TheSeeker.java:45)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.endTurn(AbstractRoom.java:415)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:267)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2615)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:825)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:376)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by SirHaesslich** [comment]
Tried it without any potions, still the same result. This time due to differences in energy amount the Dart was not topdecked but simply was in the hand with no Ethereals so I still had to end a turn with it in hand and it crashed again.

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.actions.common.MakeTempCardInDrawPileAction.<init>(Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/cards/AbstractCard;IZZ)V
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.actions.common.MakeTempCardInDrawPileAction.<init>(Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/cards/AbstractCard;IZZ)V
	at fruitymod.powers.RetrogradePower.atEndOfTurn(RetrogradePower.java:39)
	at fruitymod.characters.TheSeeker.applyEndOfTurnTriggers(TheSeeker.java:45)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.endTurn(AbstractRoom.java:415)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:267)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2615)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:825)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:376)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by SirHaesslich** [comment]
Game crashed after playing Strike on a fungibeast while being under the effect of Power Overwhelming

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.actions.common.MakeTempCardInDrawPileAction.<init>(Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/cards/AbstractCard;IZZ)V
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.actions.common.MakeTempCardInDrawPileAction.<init>(Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/cards/AbstractCard;IZZ)V
	at fruitymod.powers.PowerOverwhelmingPower.onUseCard(PowerOverwhelmingPower.java:39)
	at com.megacrit.cardcrawl.actions.utility.UseCardAction.<init>(UseCardAction.java:34)
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1428)
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:284)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:148)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:255)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2615)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:825)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:376)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by fiiiiilth** [comment]
Yeah, MakeTempCardInDrawPileAction was changed in Weekly Patch 30. There are a lot of cards and powers that are gonna cause the same crash, but it's an easy fix. I should have a new release out soonish.

**Comment by fiiiiilth** [comment]
@SirHaesslich [New release is out now](https://github.com/gskleres/FruityMod-StS/releases/tag/v0.6.7).

I'm also interested in your opinion on the new Stroke of Genius, since you had specific feedback on it in the past.

**Comment by SirHaesslich** [comment]
@fiiiiilth  it DEFINITELY does not feel underpowered now, it is very flexible and with big impact potential(albeit slightly inconsistent, but that is a reasonable, unavoidable and needed downside). Now I am worried if it is slightly too strong, although it did not feel like that when I was playing it. Thank you for your work.
