### ISSUE TITLE
Vortex crashed the Game

### ISSUE THREAD

**Issue by MrKoya007** [gskleres/FruityMod-StS#191]
Hi Guys,

I wanted to play your mod again. After I picked up a Vortex and tried to play it it instantly crashed my game. disabled all other mod and tried again. same outcome

here`s the crash log:

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.actions.common.MakeTempCardInDrawPileAction.<init>(Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/cards/AbstractCard;IZZ)V
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.actions.common.MakeTempCardInDrawPileAction.<init>(Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/cards/AbstractCard;IZZ)V
	at fruitymod.cards.Vortex.use(Vortex.java:38)
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1426)
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:284)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:148)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:255)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2629)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:825)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:376)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by fiiiiilth** [comment]
There are a lot of cards that will crash for the same reason right now due to a change in the base game. I've fixed them up and I'm checking on a few other things. There should be a new release out today, assuming my internet holds it together long enough.

**Comment by MrKoya007** [comment]
Wow thx for the quick answer!!

**Comment by fiiiiilth** [comment]
@MrKoya007 No problem! [New release is out now](https://github.com/gskleres/FruityMod-StS/releases/tag/v0.6.7).

Gonna close this issue, but please feel free to open more issues with any other crashes and feedback.

Enjoy!
