### ISSUE TITLE
Card Compendium CTD

### ISSUE THREAD

**Issue by Lunaraia** [gskleres/FruityMod-StS#194]
This bug report can't follow normal structures as its... complicated.

I were playing around with the Juggernaut, using the console commands to set up a custom run for myself, however I were having issues getting rid of thecrds in his deck, no matter what I tried they would just not go away, so in the end I broke down and jsut tried landom letters, including those of other classes, lo and behold I did manage to remove them, using the Seekers Strike_P and Defend_P values, quite confused by this I went to the compendium to check on the seeker cards and I instantly had a CTD (Crash To Desktop) luckily I had Debug on and it caught the following error, now whether this is caused by the Juggernaut and The Seeker having the same Strike and Defend names for their cards of whether this is something else I do not know.

Exception: java.lang.NullPointerException
14:49:42.222 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at fruitymod.cards.Dazed_P.updateEnigmaValue(Dazed_P.java:55) ~[FruityMod.jar:?]
	at fruitymod.cards.Dazed_P.update(Dazed_P.java:67) ~[FruityMod.jar:?]
	at com.megacrit.cardcrawl.screens.compendium.CardLibraryScreen.updateCards(CardLibraryScreen.java:361) ~[?:?]
	at com.megacrit.cardcrawl.screens.compendium.CardLibraryScreen.update(CardLibraryScreen.java:191) ~[?:?]
	at com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.update(MainMenuScreen.java:206) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:700) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:376) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
14:49:42.239 INFO core.CardCrawlGame> PAUSE()
14:49:42.239 INFO core.CardCrawlGame> Game shutting down...
14:49:42.239 INFO helpers.FileSaver> Save thread interrupted!
14:49:42.240 INFO helpers.FileSaver> Save thread will die now.
Game closed.

**Comment by fiiiiilth** [comment]
Thanks for letting me know.

Looks like the `update()` function was still causing issues sometimes when the player was null. This should be fixed in the next release.
