### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TheNekromate** [gskleres/FruityMod-StS#225]
## Expected Behavior
Starting the game 

## Actual Behavior
Crashing

## Steps to Reproduce the Problem

  1.Start ModTheSpire
   2.Start the game with BaseMod and Fruity

## Specifications

  - Version:
    ModVersion Info:
    Java version (1.8.0_181)
    Slay the Spire (08-30-2018)
    ModTheSpire (3.1.0)
    Mod list:
    basemod (3.1.1)
    fruitymod-sts (0.6.9)
  - Platform:Windows 10
  - Subsystem:Erm...What is a Subsystem?
  - Crash Log:
Running with debug mode turned ON...

ModVersion Info:
 - Java version (1.8.0_181)
 - Slay the Spire (08-30-2018)
 - ModTheSpire (3.1.0)
Mod list:
 - basemod (3.1.1)
 - fruitymod-sts (0.6.9)

Begin patching...
Finding core patches...
Finding patches...
com.evacipated.cardcrawl.modthespire.patcher.PatchingException: fruitymod.patches.BackToBasicsPatch
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:217)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:176)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:192)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:272)
	at java.lang.Thread.run(Unknown Source)
Caused by: javassist.NotFoundException: com.megacrit.cardcrawl.events.thecity.BackToBasics
	at javassist.ClassPool.get(ClassPool.java:445)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:211)
	... 4 more

**Comment by boommies** [comment]
Reproduced with 0.6.9.

A new 0.7.1 was just published, which fixes the issue.  Can you try that and verify the fix?

https://github.com/gskleres/FruityMod-StS/releases/tag/0.7.1

**Comment by boommies** [comment]
Closing
