### ISSUE TITLE
This is what i get when i run it now with just basemod (probably just new version of sts causing this?)

### ISSUE THREAD

**Issue by Tremor61** [gskleres/FruityMod-StS#232]
## Actual Behavior
java.lang.RuntimeException: failed to browse jar
	at org.scannotation.archiveiterator.JarIterator.setNext(JarIterator.java:52)
	at org.scannotation.archiveiterator.JarIterator.next(JarIterator.java:59)
	at org.scannotation.AnnotationDB.scanArchives(AnnotationDB.java:326)
	at com.evacipated.cardcrawl.modthespire.Patcher.findPatches(Patcher.java:69)
	at com.evacipated.cardcrawl.modthespire.Patcher.findPatches(Patcher.java:54)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:192)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:272)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.zip.ZipException: invalid entry size (expected 245451 but got 245453 bytes)
	at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:384)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
	at java.util.jar.JarInputStream.read(JarInputStream.java:207)
	at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:140)
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:118)
	at java.util.jar.JarInputStream.getNextEntry(JarInputStream.java:142)
	at java.util.jar.JarInputStream.getNextJarEntry(JarInputStream.java:179)
	at org.scannotation.archiveiterator.JarIterator.setNext(JarIterator.java:43)
	... 7 more

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by boommies** [comment]
Confirmed when I run with the new version of BaseMod-3.2.1.
Confirmed when I run with version BaseMod-3.2.0 as well.

Also confirmed that when I change back to BaseMod-3.1.1, the game starts up fine.  If you want a temporary workaround, you should be able to use BaseMod-3.1.1 for now.

Just to make sure that I fix your issue, can you provide the following?
- SlayTheSpire Version
- ModTheSpire Version
- BaseMod Version

**Comment by Tremor61** [comment]
I'm thinking that its modthespire (which is still 3.1.0 bc i didnt see a new update for that) everything else is up-to-date. (Basemod is 3.2.1, sts is 9-6-18)
