### ISSUE TITLE
Need to update MindblastEffect used by VoidRay, MeteorShower

### ISSUE THREAD

**Issue by SilentJ28** [gskleres/FruityMod-StS#233]
MindBlastEffect seems to have updated in latest base mod / game.

Causes a crash when used by VoidRay.

Witch mod had the same issue and was fixed in this commit: https://github.com/gygrazok/witchmod/commit/f58f34e1631466eab4dea28d1d1a635c23ad5d43
https://github.com/gygrazok/witchmod/issues/26

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.vfx.combat.MindblastEffect.<init>(FF)V
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.vfx.combat.MindblastEffect.<init>(FF)V
	at fruitymod.seeker.cards.VoidRay.use(VoidRay.java:41)
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1476)
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:294)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:148)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:258)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2674)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:893)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:466)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by SilentJ28** [comment]
https://github.com/gygrazok/witchmod/issues/26 where same bug reported on witch mod

**Comment by SilentJ28** [comment]
This is the code change that might be needed: https://github.com/gskleres/FruityMod-StS/compare/master...SilentJ28:patch-1
Unsure if this has dependencies on newer versions of base mod etc and don't know how to build and verify this myself

**Comment by SilentJ28** [comment]
MeteorShower (and any other card that uses MindBlastEffect) has the same issue

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.vfx.combat.MindblastEffect.<init>(FF)V
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.vfx.combat.MindblastEffect.<init>(FF)V
	at fruitymod.seeker.cards.MeteorShower.use(MeteorShower.java:37)
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1476)
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:294)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:148)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:258)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2674)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:893)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:466)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by SilentJ28** [comment]
With the changes in https://github.com/gskleres/FruityMod-StS/pull/234 I was able to rebuild the mod and continue the saved game without issues

**Comment by SirHaesslich** [comment]
Same issue here, same crash log.

**Comment by boommies** [comment]
This should be fixed with @SilentJ28's PR that was accepted in release v1.0.1 - https://github.com/gskleres/FruityMod-StS/releases/tag/v1.0.1
